#!/bin/zsh

set -e

gamemode="${1:-osu}"

print "gamemode=$gamemode"

while IFS= read -r event; do
    case "$event" in
        osu|taiko|catch|mania)
            gamemode="$event"
            print "gamemode=$gamemode"
            ;;
        *)
            print "$gamemode $event"
            ;;
    esac
done
