name: deploy-pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: setup-pages
        uses: actions/configure-pages@v5

      - name: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
